// Configurator/src/views/Motors.vue
<script lang="ts">
import Motor from "@components/Motor.vue";
import { defineComponent } from "vue";
import { MspFn, MspVersion } from "@utils/msp";
import { intToLeBytes, leBytesToInt } from "@utils/utils";
import { useLogStore } from "@stores/logStore";
import { type Command } from "@utils/types";
import { sendCommand, addOnDisconnectHandler, removeOnDisconnectHandler, addOnCommandHandler, removeOnCommandHandler } from "@/communication/serial";

export default defineComponent({
	name: "Motors",
	components: { Motor },
	data() {
		return {
			motors: [1000, 1000, 1000, 1000], // current values
			throttles: [1000, 1000, 1000, 1000], // commands
			motorMapping: [3, 1, 2, 0],
			sendInterval: -1,
			getMotorsInterval: -1,
			configuratorLog: useLogStore(),
		};
	},
	mounted() {
		this.getMotorsInterval = setInterval(() => {
			sendCommand('request', MspFn.GET_MOTOR);
		}, 100);
		addOnDisconnectHandler(this.stopMotors);
		addOnCommandHandler(this.onCommand);
	},
	unmounted() {
		clearInterval(this.getMotorsInterval);
		clearInterval(this.sendInterval);
		removeOnDisconnectHandler(this.stopMotors);
		removeOnCommandHandler(this.onCommand);
	},
	methods: {
		spinMotor(motor: number) {
			this.throttles = [1000, 1000, 1000, 1000];
			this.throttles[motor] = 1075;
		},
		stopMotors() {
			this.throttles = [1000, 1000, 1000, 1000];
			setTimeout(() => {
				clearInterval(this.sendInterval);
			}, 200);
		},
		startMotors() {
			clearInterval(this.sendInterval);
			this.sendInterval = setInterval(() => {
				sendCommand('request', MspFn.SET_MOTOR, MspVersion.V2, this.throttlesU8);
			}, 100);
		},
		onCommand(command: Command) {
			if (command.cmdType === 'response') {
				switch (command.command) {
					case MspFn.GET_MOTOR:
						{
							const m: number[] = [];
							for (let i = 0; i < 4; i++) {
								m.push(leBytesToInt(command.data.slice(i * 2, i * 2 + 2)));
							}
							this.motors = m;
						}
						break;
				}
			}
		}
	},
	computed: {
		throttlesU8() {
			return [
				...intToLeBytes(this.throttles[0], 2),
				...intToLeBytes(this.throttles[1], 2),
				...intToLeBytes(this.throttles[2], 2),
				...intToLeBytes(this.throttles[3], 2),
			]
		},
	},
})
</script>
<template>
	<div>
		<button @click="() => spinMotor(0)">Spin RR</button>
		<button @click="() => spinMotor(1)">Spin FR</button>
		<button @click="() => spinMotor(2)">Spin RL</button>
		<button @click="() => spinMotor(3)">Spin FL</button>
		<button @click="() => stopMotors()">Stop</button>
		<button @click="() => startMotors()">Start</button>
		<div class="quadPreview">
			<Motor v-for="m in motorMapping" :throttlePct="(motors[m] - 1000) / 10" />
		</div>
	</div>
</template>

<style scoped>
button {
	color: black;
}

.quadPreview {
	display: grid;
	grid-template-columns: 1fr 1fr;
	grid-template-rows: 1fr 1fr;
	grid-gap: 2rem;
	width: 30vw;
	height: 30vw;
}
</style>

// configurator/src/routes/motors/+page.svelte
<script lang="ts">
	import { port, type Command, ConfigCmd } from '../../stores';
	import { onMount, onDestroy } from 'svelte';
	import Motor from './motor.svelte';
	import { leBytesToInt } from '../../utils';
	const motorMapping = [3, 1, 2, 0];
	let int = -1;
	let throttles = [0, 0, 0, 0];
	let throttlesU8 = [0, 0, 0, 0, 0, 0, 0, 0];
	$: throttlesU8 = [
		throttles[0] & 0xff,
		throttles[0] >> 8,
		throttles[1] & 0xff,
		throttles[1] >> 8,
		throttles[2] & 0xff,
		throttles[2] >> 8,
		throttles[3] & 0xff,
		throttles[3] >> 8
	];
	$: handleCommand($port);
	function handleCommand(command: Command) {
		if (command.command === (ConfigCmd.GET_MOTORS | 0x4000)) {
			const m = [] as number[];
			for (let i = 0; i < 4; i++) {
				m.push(leBytesToInt(command.data.slice(i * 2, i * 2 + 2)));
			}
			motors = m;
		}
	}
	let motors = [0, 0, 0, 0];
	let getMotorsInterval = 0;
	function startMotors() {
		clearInterval(int);
		int = setInterval(() => {
			port.sendCommand(11, throttlesU8);
		}, 100);
	}
	function stopMotors() {
		throttles = [0, 0, 0, 0];
		setTimeout(() => {
			clearInterval(int);
		}, 200);
	}
	function spinMotor(motor: number) {
		throttles = [0, 0, 0, 0];
		throttles[motor] = 150;
		throttles = [...throttles];
	}
	onMount(() => {
		getMotorsInterval = setInterval(() => {
			port.sendCommand(ConfigCmd.GET_MOTORS);
		}, 100);
	});
	onDestroy(() => {
		clearInterval(getMotorsInterval);
		stopMotors();
	});
</script>

<div>
	<button on:click={() => spinMotor(0)}>Spin RR</button>
	<button on:click={() => spinMotor(1)}>Spin FR</button>
	<button on:click={() => spinMotor(2)}>Spin RL</button>
	<button on:click={() => spinMotor(3)}>Spin FL</button>
	<button on:click={() => stopMotors()}>Stop</button>
	<button on:click={() => startMotors()}>Start</button>
	<div class="quadPreview">
		{#each motors.map((m, i) => motors[motorMapping[i]]) as motor}
			<Motor throttlePct={motor / 20} />
		{/each}
	</div>
</div>

<style>
	button {
		color: black;
	}

	.quadPreview {
		display: grid;
		grid-template-columns: 1fr 1fr;
		grid-template-rows: 1fr 1fr;
		grid-gap: 2rem;
		width: 30vw;
		height: 30vw;
	}
</style>
